- name: install web-server tomcat
  hosts: web
  become: yes

  tasks:

  - name: apt update
    apt: 
      update_cache: yes

  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat is started
    service:
      name: tomcat9
      state: started

- name: install build
  hosts: db
  become: yes

  tasks:

  - name: apt update
    apt: 
      update_cache: yes

  - name: Ensure java is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present

  - name: Ensure git is present
    apt: 
      name: git 
      state: present

  - name: Fetch application on git
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git 
      dest: /home/app

  - name: build webapp
    shell: mvn package
    args:
      chdir: '/home/app'

  - name: Fetch webapp-file
    fetch:
      src: /home/app/target/hello-1.0.war
      dest: /home/app/hello-1.0.war
      flat: yes

  - name: Copy webapp-file
    copy:
      src: /home/app/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war