- name: install web-server tomcat
  hosts: web
  become: yes

  tasks:

  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      update_cash: yes
      state: present

  - name: Ensure tomcat is started
    service:
      name: tomcat9
      state: started

- name: install build
  hosts: db
  become: yes

  tasks:

  - name: apt update
    apt: 
      update_cache: yes

  - name: Ensure java is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present

  - name: Ensure git is present
    apt: 
      name: git 
      state: present

  - name: Deploy our awesome application
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git 
      dest: /home/app

  - name: build webapp
    shell: mvn package
    arg:
      chdir: /home/app